[package]
name = "encrpt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies] 
aes-gcm-siv = "0.10.3"
base64 = "0.13.0"
hex = "0.4.3"
rand = "0.8.5"
sha3 = "0.10.1"